### ISSUE TITLE
Issue deserializing List<object> with null value

### ISSUE THREAD

**Issue by bpaczkowski** [wojtpl2/ExtendedXmlSerializer#201]
I have the following example class:

```
public class TestClass
{
	public List<object> TestProperty { get; set; } = new List<object> { null };
}
```

Serializing it generates the following xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<Program-TestClass xmlns="clr-namespace:XmlMigrator;assembly=XmlMigrator" xmlns:sys="https://extendedxmlserializer.github.io/system">
   <TestProperty>
      <Capacity>4</Capacity>
      <Null xmlns="https://extendedxmlserializer.github.io/v2" />
   </TestProperty>
</Program-TestClass>
```

When deserializing it I get the following exception:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.References.DeferredContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.RuntimeSerialization.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Get(IFormatReader reader)
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.RootInstanceExtension.Serializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionContentsHandler.Handle(IListInnerContent contents, IReader reader)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IListInnerContent contents, IReader reader)
   at ExtendedXmlSerializer.ContentModel.Collections.CollectionInnerContentHandler.Execute(IInnerContent parameter)
   at ExtendedXmlSerializer.Core.SelectedCommand`1.Execute(T parameter)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member)
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter)
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceReader.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.RootInstanceExtension.Serializer.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Get(IFormatReader parameter)
   at ExtendedXmlSerializer.Read`1.Get(T parameter)
   at ExtendedXmlSerializer.Serializer`2.Deserialize(TRead reader)
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Deserialize(XmlReader reader)
   at XmlMigrator.Program.Main() in C:\...\Program.cs:line 159
```

ExtendedXmlSerializer version: 2.1.6

**Comment by Mike-EEE** [comment]
Wow!  I am SHOCKED that this happens!  I thought for sure we had already addressed this but in looking back it is for properties and not collections, doh! 

I just now checked in a fix.  Please get the latest from our preview feed here:
https://www.myget.org/F/wojtpl2/api/v3/index.json

Let me know if everything is OK and I will push 2.1.7. :)

Thanks for reporting this. 👍

**Comment by bpaczkowski** [comment]
2.1.6 is the newest on that nuget feed. It shows it as updated today a few hours ago, but the fix doesn't seem to be in that version. Are you sure you pushed the correct dll? 🙂

**Comment by Mike-EEE** [comment]
Ah you might be running into #184.  Try clearing out your local nuget copy of the `ExtendedXmlSerializer` in your `.nuget/packages` and try again.  It *should* get you the right package.  It's basically a caching issue we are running into with the preview feed.

**Comment by Mike-EEE** [comment]
OK... I've pushed `2.1.7`.  It should be public here in the next hour.  Please let me know if you run into any problems and I will help out to see what's wrong.  Closing this issue for now.

**Comment by bpaczkowski** [comment]
Clearing the cache indeed worked. The reported issue is also fixed, thanks for the quick response!
