### ISSUE TITLE
Serialization behavior

### ISSUE THREAD

**Issue by cm4ker** [wojtpl2/ExtendedXmlSerializer#218]
I'm starting integrate ExtendedXmlSerializer to my pet project instead of standard System.Xml. And I have some troubles. Can you suggest how to be in the next situation: 

Look at the small repro
```csharp
    internal class Program
    {
        public static void Main(string[] args)
        {
            var xs = new ConfigurationContainer().Create();
            using (var xw = (XmlWriter.Create(Console.Out)))
                xs.Serialize(xw, new SerializedObject());
        }
    }

    public class MyListImpl<T> : List<T>
    {
        private readonly object _owner;

        public MyListImpl(object owner)
        {
            _owner = owner;
        }
    }

    public class SerializedObject
    {
        public SerializedObject()
        {
            MyListImpl = new MyListImpl<string>(this);
            MyListImpl.Add("Test");
        }

        public MyListImpl<string> MyListImpl { get; }
    }
```

I have class look like ```SerializedObject``` (it has the read-only custom list with generic argument property that have not parameter less constructor), but the collection instantiate during SerializedObject construct. It works like a charm in System.Xml but it throw the exception then I try serialize it with default settings using the ExtendedXmlSerializer.

```
 System.InvalidOperationException: The serializer for type 'ProjectForTests.MyListImpl`1[System.String]' could not be found.  Please ensure that the type is a valid type can be activated.  The default
 behavior requires an empty public constructor on the (non-abstract) class to activate.
```

I have a lot of places with the same code and I can't and parameter less constructor (I have to guarantee the client what the collection know about the parent). 

How can I say to the EXS: "If property type like this: ProjectForTests.MyListImpl<TSomeType> please don't try to create this. The property already created by the owner instance."
 
Thank you.

**Comment by Mike-EEE** [comment]
Are you able to make that `MyListImpl<T>._owner` a public property instead, @cm4ker?

If so, you can use my favorite feature of EXS, parameterized content (which follows [protobuf serialization rules found here](https://blog.marcgravell.com/2011/08/automatic-serialization-whats-in-tuple.html)):

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/1056de9fa1faf9a1c43e37b7375555a741babd05/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue218Tests.cs#L12-L27

**Comment by cm4ker** [comment]
> Are you able to make that MyListImpl<T>._owner a public property instead
Hi there, @Mike-EEE! Yea can make it public but I don't need the parent in out xml. I just want this look in xml like this then I seralize:

```xml
<ParentObject>
    <Collection>
        <!-- I won't add here extra information for client -->
        <ChildItem />
        <ChildItem />
    </Collection>
<ParentObject>
```

And restore the state after deserialization;

**Comment by Mike-EEE** [comment]
Ah, the `Cycle` extension method is found in our testing library to cycle the objects under test to ensure that they are serialized properly.  It doesn't make much sense to do that outside of testing. :)

I'm afraid I do not understand what you mean in regards to the serialization.  Are you saying the current serialization is not as expected?  

Taking your initial request/example:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/8780307fbe0401bc42b90e233c62456efd48a536/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue218Tests.cs#L23-L47

This is how it looks for me:

```
<?xml version="1.0" encoding="utf-8"?>
<Issue218Tests-SerializedObject xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:identity="1" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests">
	<MyListImpl>
		<Owner exs:type="Issue218Tests-SerializedObject" exs:reference="1" />
		<Capacity>4</Capacity>
		<string xmlns="https://extendedxmlserializer.github.io/system">Test</string>
		<string xmlns="https://extendedxmlserializer.github.io/system">One</string>
		<string xmlns="https://extendedxmlserializer.github.io/system">Two</string>
	</MyListImpl>
</Issue218Tests-SerializedObject>
```

That looks pretty close to what you are aiming for, unless I am misunderstanding something fundamental here.  Please let me know if so. :)

**Comment by cm4ker** [comment]
Yea this is exact what I want. Thank you!

**Comment by Mike-EEE** [comment]
Cool.  If you have any additional/further questions, please feel free to ask. :)

**Comment by cm4ker** [comment]
@Mike-EEE

**Comment by Mike-EEE** [comment]
You got me here, @cm4ker. :) What do you mean by not instantiate?  The property is instantiated by the class, or however the class is defined, so that is outside of ExtendedXmlSerializer's scope.

Are you saying you want to ignore it altogether?  FWIW, ExtendedXmlSerializer's default behavior is to add items to a read only collection.  Please let me know what I have misunderstood here, and/or feel free to post some code that shows where you are having the trouble.  Failing tests are preferable. 👍

**Comment by cm4ker** [comment]
I'm  add the test for this. This is throw the exception for now. I not add any assertion.

This is a original stack trace what I have
```
System.InvalidOperationException : The serializer for type 'ExtendedXmlSerializer.Tests.ReportedIssues.Issue218Tests+ChildList' could not be found.  Please ensure that the type is a valid type can be activated.  The default behavior requires an empty public constructor on the (non-abstract) class to activate.
   at ExtendedXmlSerializer.ContentModel.RuntimeSerialization.Get(TypeInfo parameter) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\RuntimeSerialization.cs:line 45
   at ExtendedXmlSerializer.ContentModel.RuntimeSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\RuntimeSerializer.cs:line 48
   at ExtendedXmlSerializer.ContentModel.Members.VariableTypedMemberWriter.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\VariableTypedMemberWriter.cs:line 63
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Write(IFormatWriter writer, T instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 47
   at ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\Enclosure.cs:line 51
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializers.Writer.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializers.cs:line 101
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:line 46
   at ExtendedXmlSerializer.ContentModel.Members.MemberListWriter.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberListWriter.cs:line 43
   at ExtendedXmlSerializer.ContentModel.Serializer`1.Write(IFormatWriter writer, T instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 47
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceSerializer.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\ReferenceSerializer.cs:line 71
   at ExtendedXmlSerializer.ContentModel.Content.Enclosure`1.Write(IFormatWriter writer, T instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\Enclosure.cs:line 51
   at ExtendedXmlSerializer.ContentModel.SerializerAdapter`1.Write(IFormatWriter writer, T instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\SerializerAdapter.cs:line 66
   at ExtendedXmlSerializer.ExtensionModel.References.CircularReferenceEnabledSerialization.Container.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\References\CircularReferenceEnabledSerialization.cs:line 51
   at ExtendedXmlSerializer.ExtensionModel.RootInstanceExtension.Serializer.Write(IFormatWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\RootInstanceExtension.cs:line 70
   at ExtendedXmlSerializer.Write`1.Execute(Writing`1 parameter) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\Write.cs:line 43
   at ExtendedXmlSerializer.Serializer`2.Serialize(TWrite writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\Serializer.cs:line 41
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:line 40
   at ExtendedXmlSerializer.Tests.Support.SerializationSupport.Serialize(XmlWriter writer, Object instance) in C:\projects\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\Support\SerializationSupport.cs:line 56
   at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\InstanceFormatter.cs:line 55
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, IXmlWriterFactory factory, Func`1 stream, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 259
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Serialize(IExtendedXmlSerializer this, Object instance) in C:\projects\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 245
   at ExtendedXmlSerializer.Tests.ReportedIssues.Issue218Tests.VerifySerializeWithParent() in C:\projects\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\ReportedIssues\Issue218Tests.cs:line 50
```

**Comment by cm4ker** [comment]
This is strange. Why it looks on the constructor during serialization? We are already have the constructed object.

**Comment by cm4ker** [comment]
> there must be exactly one interesting constructor, with parameters that are a case-insensitive match for each field/property in some order (i.e. there must be an obvious 1:1 mapping between members and constructor parameter names)

Oh. Now I see. The property is a argument which will pass then we construct object during deserialization.

I can't understand the logic. For example then we serialize member which is read only (has only public ```get``` method, has not public ```set```) we know what: the object initialize it by himself (or if we make it the ```internal``` by another object I think this is the same as private in this). Simple if the property is collection and it is a read only we simple can skip analyze it constructors (we don't need to care about construncting it during deserialization).

How can  I apply logic I described above to the EXS?

**Comment by Mike-EEE** [comment]
Unfortunately, I am having a bit of trouble understanding what you are meaning, @cm4ker.  This scenario that you are after (if I understand what I _think_ I understand 😆) is possible.  You just need to rename `_owner` to `owner` and make it `public` like the test demonstrates.

Whatever `owner` is will be serialized as well (if it abides by the parameterized content rules, that is).  

If you can demonstrate your issue/question with code/PR I think that would work best for me. 👍 	

Also, to (hopefully!) help out further, readonly collections are supported by default, without the need for parameterized content:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/77b686c10209bbf942235c9d540c5fe9c32a1dcf/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue218Tests.cs#L73-L91
