### ISSUE TITLE
Deserialize collection of elements

### ISSUE THREAD

**Issue by martin211** [wojtpl2/ExtendedXmlSerializer#243]
Hi,

I want to deserialze a collection. My XML structure
```
<MediaContainer size='1'> 
    <MediaItem Name='Name1' Id='1' />
    <MediaItem Name='Name2' Id='2' />
</MediaContainer>
```
My class structure
```
public class MediaContainer
{
    [XmlAttribute("size")]
    public int Size { get; set; }

    [XmlElement("MediaItem")]
    public List<MediaItem> Items { get; set; }
}

public class MediaItem
{
    [XmlAttribute]
    public string Name { get; set; }

    [XmlAttribute]
    public string Id { get; set; }
}
```

I've tried different configuration, but it's not working.
`
var serializer = new ConfigurationContainer()
    .EnableImplicitTyping(typeof(MediaContainer), typeof(List<MediaItem>), typeof(MediaItem))
    .Type<List<MediaItem>>()
    .Create();
`
 I got exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.
    at ExtendedXmlSerializer.ReflectionModel.TypeCoercer.Get(TypeInfo parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ReflectionModel\TypeCoercer.cs:line 35
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at ExtendedXmlSerializer.ReflectionModel.SelectCoercer`2.Get(ImmutableArray`1 parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ReflectionModel\SelectCoercer.cs:line 37
   at ExtendedXmlSerializer.Core.Sources.CoercedResult`3.Get(TParameter parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CoercedResult.cs:line 37
   at ExtendedXmlSerializer.Core.Sources.CoercedResult`3.Get(TParameter parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CoercedResult.cs:line 37
   at ExtendedXmlSerializer.Core.Sources.CoercedResult`3.Get(TParameter parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\CoercedResult.cs:line 37
   at ExtendedXmlSerializer.Core.Sources.DecoratedSource`2.Get(TParameter parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Core\Sources\DecoratedSource.cs:line 32
   at ExtendedXmlSerializer.ContentModel.Collections.Lists.CreateAdapter(Object parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Collections\Lists.cs:line 47
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlListContentsActivator.Create(IFormatReader reader, Object instance, XmlContent content) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\XmlListContentsActivator.cs:line 41
   at ExtendedXmlSerializer.ExtensionModel.Xml.XmlInnerContentActivator.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\XmlInnerContentActivator.cs:line 50
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 43
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 35
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 35
   at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:line 37
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 50
   at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 59
   at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 46
   at ExtendedXmlSerializer.ContentModel.Members.Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ContentModel\Members\Extensions.cs:line 35
   at ExtendedXmlSerializer.Read`1.Get(T parameter) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\Read.cs:line 49
   at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, IXmlReaderFactory factory, Stream stream) in C:\projects\extendedxmlserializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 291
```
How I can configure container to deserialize my xml?

**Comment by wojtpl2** [comment]
@Mike-EEE You are really fast! I'm impressed.

**Comment by Mike-EEE** [comment]
Hehe thanks... good timing. :D I got back from working out to see the question and was able to do it quickly.

Supporting this project is definitely a priority. I don't want to leave you in a lurch with the mountain of code I left in your repo. 😆

**Comment by martin211** [comment]
@Mike-EEE Unfortunately your example did not help me. I cannot change the structure of source xml. I gets it from Api. It seems like you library required that all collection items should be wrapped by some root node.

**Comment by Mike-EEE** [comment]
Ah, that's too bad @martin211.   You have hit the Achilles heel of v2 as captured and described in #240.  FWIW, EXSv2's intent was to be a POCO serializer first and foremost while being able to retain as much legacy/classic functionality as possible along the way.  Unfortunately, this one issue has been a stickler and would take a bit of work to address, most likely introducing a breaking change.

One possibility is to use XSLT to convert the provided XML from the API into XML that EXS can work with and then deserialize from there.  Otherwise, you will have to use the classic XmlSerializer for your scenario.

**Comment by martin211** [comment]
@Mike-EEE Hmm... XSLT... you just gave me a good idea!!!

**Comment by Mike-EEE** [comment]
Cool. :)  XSLT is one of the very many reasons why I prefer XML over JSON, and it is meant for scenarios exactly as this where data doesn't quite match up as desired between application boundaries.

Unfortunately, it is well underutilized and misunderstood, so we get things like JSON created instead. 😁

Please let me know if you run into any issues and/or need any further assistance in your pursuit.

**Comment by Mike-EEE** [comment]
Closing this issue now as it seems to be resolved.  Please let us know if you have any further questions around our product.

**Comment by BianChengNan** [comment]
Does ExtendedXml|Serializer support serialize/deserialize such xml structures now? really need this feature.

```
<MediaContainer size='1'> 
    <MediaItem Name='Name1' Id='1' />
    <MediaItem Name='Name2' Id='2' />
</MediaContainer>

public class MediaContainer
{
    [XmlAttribute("size")]
    public int Size { get; set; }

    [XmlElement("MediaItem")]
    public List<MediaItem> Items { get; set; }
}

public class MediaItem
{
    [XmlAttribute]
    public string Name { get; set; }

    [XmlAttribute]
    public string Id { get; set; }
}
```
