### ISSUE TITLE
Properties of type IEnumerable<T> cause exceptions

### ISSUE THREAD

**Issue by hamish-milne** [wojtpl2/ExtendedXmlSerializer#93]
If I have a property like this: `public virtual IEnumerable<CswTestData> TestData => Monotonic.Concat(new CswTestData[] {Sweep}).Where(td => td != null);`

it causes the Serialize method to fail, like this:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at ExtendedXmlSerialization.Cache.ObjectAccessors.CreateMethodAddCollection(Type type, Type elementType)
   at ExtendedXmlSerialization.Cache.TypeDefinition..ctor(Type type)
   at ExtendedXmlSerialization.Cache.TypeDefinitionCache.<>c.<GetDefinition>b__3_0(Type t)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at ExtendedXmlSerialization.Cache.TypeDefinitionCache.GetDefinition(Type type)
   at ExtendedXmlSerialization.Cache.PropertieDefinition..ctor(Type type, PropertyInfo propertyInfo, String name)
   at ExtendedXmlSerialization.Cache.TypeDefinition.GetPropertieToSerialze()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at ExtendedXmlSerialization.ExtendedXmlSerializer.WriteXml(XmlWriter writer, Object o, TypeDefinition type, String name, Boolean writeReservedObject, Boolean forceSaveType)
   at ExtendedXmlSerialization.ExtendedXmlSerializer.WriteXmlArray(Object o, XmlWriter writer, TypeDefinition def, String name, Boolean forceSaveType)
   at ExtendedXmlSerialization.ExtendedXmlSerializer.WriteXml(XmlWriter writer, Object o, TypeDefinition type, String name, Boolean writeReservedObject, Boolean forceSaveType)
   at ExtendedXmlSerialization.ExtendedXmlSerializer.WriteXml(XmlWriter writer, Object o, TypeDefinition type, String name, Boolean writeReservedObject, Boolean forceSaveType)
   at ExtendedXmlSerialization.ExtendedXmlSerializer.Serialize(Object o)
```

This happens because `IEnumerable<T>` is assumed to be a collection type, and thus it tries to find an Add method, which naturally returns null. This case isn't checked, which causes this error.

Two ways to fix this:

- Use `ICollection` rather than `IEnumerable` as a collection base type. That way you know there must be an Add method - it's defined in the interface.
- Check for the case where there is no Add method and do something sensible.

**Comment by Mike-EEE** [comment]
Hi @hamish-milne thanks for reporting this.  This is indeed a limitation of v1.  We have a v2 preview branch which you can view here (take your pick, the myget is newer):

https://www.myget.org/feed/wojtpl2/package/nuget/ExtendedXmlSerializer
https://www.nuget.org/packages/ExtendedXmlSerializer/2.0.0-alpha

I would be interested in knowing your results with this.  The IEnumerable should not emit unless it is a collection (LINQ query as you have described should not qualify).

**Comment by Mike-EEE** [comment]
Hi @hamish-milne I will be closing this issue now.  Please let us know if you encounter any issues with v2 and we'll be happy to look at them for you.
