### ISSUE TITLE
Class with int[] property

### ISSUE THREAD

**Issue by wojtpl2** [wojtpl2/ExtendedXmlSerializer#99]
If you have class with array of int:
```C#
	public class TestClassWithArray
	{
		public int[] ArrayOfInt { get; set; }
	}
```
And then create object:
```C#
var expected = new TestClassWithArray() {ArrayOfInt = new int[] {1, 2, 3}};
```

Serializer works correct:
```xml
<?xml version="1.0" encoding="utf-8"?>
<TestClassWithArray xmlns="clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests">
	<ArrayOfInt>
		<int xmlns="https://extendedxmlserializer.github.io/system">1</int>
		<int xmlns="https://extendedxmlserializer.github.io/system">2</int>
		<int xmlns="https://extendedxmlserializer.github.io/system">3</int>
	</ArrayOfInt>
</TestClassWithArray>
```
But deserializer raises exception:
```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=An attempt was made to load a type with the fully qualified name of 'clr-namespace:ExtendedXmlSerializer.Tests.TestObject;assembly=ExtendedXmlSerializer.Tests:ArrayOfInt', but no type could be located with that name.
  Source=ExtendedXmlSerializer
  StackTrace:
       at ExtendedXmlSerializer.ContentModel.Extensions.GetClassification(IClassification this, IFormatReader parameter, TypeInfo defaultValue) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Extensions.cs:line 55
       at ExtendedXmlSerializer.ContentModel.Collections.ArrayReader.Get(IFormatReader parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Collections\ArrayReader.cs:line 50
       at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 40
       at ExtendedXmlSerializer.ContentModel.Members.MemberSerializer.Get(IFormatReader parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberSerializer.cs:line 44
       at ExtendedXmlSerializer.ContentModel.Members.MemberHandler.Handle(IInnerContent contents, IMemberSerializer member) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberHandler.cs:line 40
       at ExtendedXmlSerializer.ContentModel.Content.InnerContentServices.Handle(IInnerContent contents, IMemberSerializer member) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentServices.cs:line 62
       at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.IsSatisfiedBy(IInnerContent parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 52
       at ExtendedXmlSerializer.ContentModel.Members.MemberInnerContentHandler.Execute(IInnerContent parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Members\MemberInnerContentHandler.cs:line 57
       at ExtendedXmlSerializer.ContentModel.Content.InnerContentReader.Get(IFormatReader parameter) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Content\InnerContentReader.cs:line 46
       at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 40
       at ExtendedXmlSerializer.ContentModel.Serializer.Get(IFormatReader reader) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ContentModel\Serializer.cs:line 40
       at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Deserialize(XmlReader reader) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\ExtendedXmlSerializer.cs:line 63
       at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, IXmlReaderFactory factory, Stream stream) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 158
       at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, XmlReaderSettings settings, Stream stream) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 155
       at ExtendedXmlSerializer.ExtensionModel.Xml.Extensions.Deserialize[T](IExtendedXmlSerializer this, String data) in C:\Work\ExtendedXmlSerializer\src\ExtendedXmlSerializer\ExtensionModel\Xml\Extensions.cs:line 149
       at ExtendedXmlSerializer.Tests.Support.Extensions.Cycle[T](IExtendedXmlSerializer this, T instance) in C:\Work\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\Support\Extensions.cs:line 32
       at ExtendedXmlSerializer.Tests.ExtensionModel.Xml.ExtendedXmlSerializerTests.ClassWithArray() in C:\Work\ExtendedXmlSerializer\test\ExtendedXmlSerializer.Tests\ExtensionModel\Xml\ExtendedXmlSerializerTests.cs:line 246
  InnerException: 
```

**Comment by wojtpl2** [comment]
I've added ClassWithArray test.

**Comment by wojtpl2** [comment]
It was working in v1.5.

**Comment by wojtpl2** [comment]
There is lagacy test: https://github.com/wojtpl2/ExtendedXmlSerializer/blob/v2.0.0/test/ExtendedXmlSerializer.Tests.Legacy/SerializationArray.cs#L49-L55

**Comment by Mike-EEE** [comment]
This is addressed now with the latest changes.  Please re-open this issue if unexpected behavior persists.

**Comment by Mike-EEE** [comment]
(Nice find, btw. 👍 )

**Comment by umutesen** [comment]
I am getting this error when deserializing an XML string with version 2.1.2:

`An attempt was made to load a type with the fully qualified name of 'http://namespace/file.xsd:myMessage', but no type could be located with that name.`

XML:

```
<?xml version="1.0"?>
<myMessage xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://namespace/file.xsd">
  <myElement uniqueId="12345"> 
</myMessage>
```
Class:

```
    // <remarks />
    [Serializable]
    [XmlType(AnonymousType = true, Namespace = "http://namespace/file.xsd")]
    [XmlRoot("myMessage", Namespace = "http://namespace/file.xsd",
        IsNullable = false)]
    public class MyMessage
    {
        /// <remarks />
        [XmlElement("myElement")]
        public MyElementType MyElement { get; set; }
    }
```

Call to the serializer:

`_xmlSerializer.Deserialize<MyMessage>(xml)
`
